import org.apache.hadoop.fs.PathIOException;
public class FunctionUse2637 {
public void funcUse() {
PathIOException pathioexception = new PathIOException();
pathioexception.setTargetPath(null);
}
}